component_depth: 4

exclude: 
  - /SpeectInstaller/.*
  - .*\.txt*
  - .*\.ui

languages: 
  - name: cpp
    production: 
      include: 
        - /DeSpeect/Model/.*
        - /DeSpeect/Qt/.*
    test: 
      include: 
        - /DeSpeect/Test/.*
