
exclude: 
  - /SpeectInstaller/.*
  - /DeSpeect/Test/.*
  - .*\.txt*
languages: 
  - name: cpp
    production: 
      include: 
        - /DeSpeect/Model/.*
        - /DeSpeect/Qt/.*
    test: 
      include: 
        - /DeSpeect/Test/.*\.cpp
