
exclude:
  - /SpeectInstaller/.*
  - /DeSpeect/Test/.*
  - .*\.txt
  - .*\.md

component_depth: 3

languages:
    - name: cpp
    production:
        include:
            - /DeSpeect/*
            - *.cpp
    test:
        include:
            - /DeSpeect/Test/.*\.cpp
