
exclude:
  - /SpeectInstaller/.*
  - .*\.txt
  - .*\.md

component_depth: 3

languages:
    - name: cpp
    production:
        include:
            - /DeSpeect/Qt/.*\.cpp
            - /DeSpeect/Model/.*\.cpp
    test:
        include:
            - /DeSpeect/Test/.*\.cpp
